### PR TITLE
fix(🐛): Fix Android bug when dealing with string animated values

### LINKED ISSUE #300: Animated String Values on Android
While string values work great on iOS, they throw errors and crash on Android. 
Below are two examples that work great on iOS but crash or throw on Android with v1.1.0.

## Example 1

```ts
import { TextInput } from "react-native";
const AnimatedTextInput = Animated.createAnimatedComponent(TextInput);

export default () => {
  return (
    <AnimatedTextInput
        underlineColorAndroid="transparent"
        editable={false}
        text={concat("hello ", "world")}
    />
  );
};
```

Error: ConcatNode cannot be cast to a number

## Example 2

```ts
import Svg, { Path } from "react-native-svg";
import Animated from "react-native-reanimated";

const AnimatedPath = Animated.createAnimatedComponent(Path);

export default () => {
  return (
    <Svg style={styles.container} viewBox="0 0 212 239">
      <AnimatedPath
        d={concat(
          "M106,1 C156,1 229.606798,153.786405 206,201 C182.393202,248.213595 31.5199889,252.039978 6,201 C-19.5199889,149.960022 56,1 106,1 Z"
        )}
      />
    </Svg>
  );
};
```

Crashes

### PR DESCRIPTION
**Pull request by wcandillon**
This PR takes @msand and @osdnk  from #176 into consideration.

fixes #300

### CODE REVIEW

File: react-native-reanimated.d.ts [hunk 1]
```diff
@@ -311,13 +311,7 @@ declare module 'react-native-reanimated' {
...
 
     // configuration
-
-    // `addWhitelistedNativeProps` will likely be removed soon, and so is
-    // intentionally not exposed to TypeScript. If it is needed, it could be
-    // uncommented here, or just use
-    // `(Animated as any).addWhitelistedNativeProps({ myProp: true });`
-
-    // addWhitelistedNativeProps(props: { [key: string]: true }): void;
+    export function addWhitelistedNativeProps(props: { [key: string]: true }): void;
```
Comment (wcandillon) [inline react-native-reanimated.d.ts]: @msand I did not need to use this function in order to make the path animation work on Android. Is it a performance optimization to use it?

**Comment by wcandillon** [comment]
@osdnk I'm not sure why the CI fails? Please let me know if there is something that I can fix there.

File: react-native-reanimated.d.ts (hunk 1 above)
Comment (msand) [reply react-native-reanimated.d.ts]: @wcandillon I think without this the change might go from native to js and back to native, rather than stay native. But, I'm not sure, haven't read the latest source, nor placed any debug breakpoints to test this hypothesis.

Comment (osdnk) [reply react-native-reanimated.d.ts]: So yes, animating string includes JS trip, but it's ok, no?

Comment (osdnk) [reply react-native-reanimated.d.ts]: Or no, it doesn't. Hmmm, need to check!

File: android/src/main/java/com/swmansion/reanimated/nodes/PropsNode.java [hunk 2]
```diff
@@ -25,6 +25,28 @@
   private final JavaOnlyMap mPropMap;
   private final ReactStylesDiffMap mDiffMap;
 
+  private void addProp(WritableMap propMap, String key, Object value) {
+    if (value == null) {
+      propMap.putNull(key);
+    } else if (value instanceof Double) {
+      propMap.putDouble(key, (Double) value);
+    } else if (value instanceof Integer) {
```
Comment (osdnk) [inline android/src/main/java/com/swmansion/reanimated/nodes/PropsNode.java]: I think that there's no case when it's `Integer` coz JS's number is serialized to `Double`, no?

File: android/src/main/java/com/swmansion/reanimated/nodes/PropsNode.java [hunk 3]
```diff
@@ -25,6 +25,28 @@
...
+      propMap.putInt(key, (Integer) value);
+    } else if (value instanceof Number) {
+      propMap.putDouble(key, ((Number) value).doubleValue());
+    } else if (value instanceof Boolean) {
+      propMap.putBoolean(key, (Boolean) value);
+    } else if (value instanceof String) {
+      propMap.putString(key, (String) value);
+    } else if (value instanceof WritableArray) {
```
Comment (osdnk) [inline android/src/main/java/com/swmansion/reanimated/nodes/PropsNode.java]: Also, it's never another map, no? `Boolean`, `Number` and `String` are enough.

Can we reuse it here https://github.com/kmagiera/react-native-reanimated/pull/311/files#diff-4f72bb0bf303947e60ceb110eb069188R99? It appears to be a similar code.

File: react-native-reanimated.d.ts (hunk 1 above)
Comment (osdnk) [reply react-native-reanimated.d.ts]: Sorry, yes it's animating with native drivers as well 😅

File: android/src/main/java/com/swmansion/reanimated/nodes/PropsNode.java (hunk 3 above)
Comment (wcandillon) [reply android/src/main/java/com/swmansion/reanimated/nodes/PropsNode.java]: I agree. Can it be `Array` though then? 🤔

Comment (wcandillon) [reply android/src/main/java/com/swmansion/reanimated/nodes/PropsNode.java]: The logic at https://github.com/kmagiera/react-native-reanimated/pull/311/files#diff-4f72bb0bf303947e60ceb110eb069188R99 seems different, do you think that I can unify both?

Comment (wcandillon) [reply android/src/main/java/com/swmansion/reanimated/nodes/PropsNode.java]: you are correct!

**Comment by wcandillon** [comment]
Review comments implemented 😎

File: android/src/main/java/com/swmansion/reanimated/nodes/PropsNode.java (hunk 2 above)
Comment (msand) [reply android/src/main/java/com/swmansion/reanimated/nodes/PropsNode.java]: Colors can actually be represented as Integer 
https://github.com/facebook/react-native/blob/0ee5f68929610106ee6864baa04ea90be0fc5160/Libraries/StyleSheet/__tests__/processColor-test.js

https://github.com/facebook/react-native/blob/0ee5f68929610106ee6864baa04ea90be0fc5160/Libraries/StyleSheet/__tests__/normalizeColor-test.js

https://github.com/facebook/react-native/blob/a4cc519a52882a6b08825ecdb15e1c9411c0197d/ReactCommon/fabric/graphics/platform/cxx/Color.h

Also, in react-native-svg:
https://github.com/react-native-community/react-native-svg/blob/master/lib/extract/extractColor.js#L406-L417

Comment (wcandillon) [reply android/src/main/java/com/swmansion/reanimated/nodes/PropsNode.java]: @msand can you check if the latest version of the patch is in order? We now look at the value type instead of its Java instance.

**Comment by simonbuerger** [comment]
Nice. FYI the Example 1 from #300 still crashes on Android with a different error using this branch.

`java.lang.String cannot be cast to com.facebook.react.bridge.WritableMap`

File: android/src/main/java/com/swmansion/reanimated/nodes/PropsNode.java [hunk 4]
```diff
@@ -73,28 +93,17 @@ protected Double evaluate() {
...
-            case String:
-              dest.putString(key, style.getString(key));
-              break;
-            case Array:
-              dest.putArray(key, (WritableArray) style.getArray(key));
-              break;
-            default:
-              throw new IllegalArgumentException("Unexpected type " + type);
-          }
+          addProp(dest, key, node.value());
```
Comment (wcandillon) [inline android/src/main/java/com/swmansion/reanimated/nodes/PropsNode.java]: I just tested this branch and it works great for my use case but how can I test that this particular refactoring doesn't cause any regression?

**Comment by wcandillon** [comment]
@osdnk I implemented the review comment, however, I'm not sure that factoring of the StyleNode casting that you requested works well. Could you provide me with an example so I can test it?

File: android/src/main/java/com/swmansion/reanimated/nodes/PropsNode.java (hunk 4 above)
Comment (simonbuerger) [reply android/src/main/java/com/swmansion/reanimated/nodes/PropsNode.java]: I don't think this is going to work. Doesn't seem that the two implementations are compatible here. node.value() in this case won't get the individual style prop values

Comment (wcandillon) [reply android/src/main/java/com/swmansion/reanimated/nodes/PropsNode.java]: yes that makes sense 👍🏻

**Comment by wcandillon** [comment]
@osdnk Just try this PR again, works great. Here are the two use cases it fixes: https://gist.github.com/wcandillon/87f8463e7a6c4fd3eb183c0626c17ae9.
Please let me know if I can help to get this merged.

File: android/src/main/java/com/swmansion/reanimated/nodes/PropsNode.java [hunk 5]
```diff
@@ -25,6 +25,28 @@
   private final JavaOnlyMap mPropMap;
   private final ReactStylesDiffMap mDiffMap;
 
+  private void addProp(WritableMap propMap, String key, Object value) {
```
Comment (kmagiera) [inline android/src/main/java/com/swmansion/reanimated/nodes/PropsNode.java]:
```suggestion
  private static void addProp(WritableMap propMap, String key, Object value) {
```

Comment (kmagiera) [reply android/src/main/java/com/swmansion/reanimated/nodes/PropsNode.java]: The PR looks good, I'm just going to commit my suggestion and merge it afterwards

Comment (kmagiera) [reply android/src/main/java/com/swmansion/reanimated/nodes/PropsNode.java]: OMG, I can't commit it apparently, because the PR is from your fork

**Comment by wcandillon** [comment]
@kmagiera the change is committed. So exciting :)

**Comment by kmagiera** [comment]
Great job, and sorry for a long wait here. Will just need CI to complete and will merge soon
